#
import pandas as pd
from os.path import join

configfile: 'config/config.yml'

#load participants.tsv file, and strip off sub- from participant_id column
df = pd.read_table(config['participants_tsv'])
subjects = df.participant_id.to_list() 
subjects = [ s.strip('sub-') for s in subjects ]

hemis = 'L R'.split()
surfaces = 'midthickness inner outer'.split()
subfields = 'Subiculum CA1 CA2 CA3 CA4'.split()
subgroups = 'ipsilateral_TLE contralateral_TLE bilateral_TLE allAffected_TLE all_TLE controls'.split()
hippunfold_metrics = config['hippunfold_metrics_for_analysis']

#bids-naming for subject and template (only alphanumeric characters)
wildcard_constraints:
    subject="[a-zA-Z0-9]+",
    hemi="[a-zA-Z0-9]+",
    surface="[a-zA-Z0-9]+",
    subfield="[a-zA-Z0-9]+",

localrules: all

include: 'rules/hippunfold_TLE_subfields_displacement_metric.smk'
include: 'rules/hippunfold_TLE_subfields_additional_metrics.smk'
include: 'rules/hippunfold_TLE_subfields_volumetry.smk'

rule all:
    input:
        group_CA1_tsv_subfield_displacement_spaceUnfold_mPD_atEachAP_dir = expand('results/hippunfold_morphometry/group_{metric}_analysis/surface-{surface}/', metric='displacement', surface=surfaces),
        group_CA1_tsv_subfield_displacement_softSmoothed_spaceUnfold_mPD_atEachAP_dir = expand('results/hippunfold_morphometry/group_{metric}_analysis_smoothedSoft/surface-{surface}/', metric='displacement', surface=surfaces),
        #Additional Hippunfold Metrics for comparison:
        group_CA1_tsv_subfield_metric_spaceUnfold_mPD_atEachAP_dir = expand('results/hippunfold_morphometry/group_{metric}_analyses/surface-{surface}/', metric=hippunfold_metrics, surface='midthickness'), 
        #Volumetry for comparison
        group_volumetry_T1w_subfields_tsv_dir = 'results/hippunfold_volumetry/group_volumetry/',
        stats_group_volumetry_T1w_subfields_tsv_dir = 'results/hippunfold_volumetry/group_volumetry_stats/',


