### Configureable variables
#1) Paths to participants and demographics tsvs
participants_tsv: 'config/participants.tsv'
demographics_tsv: 'config/demographics.tsv'

#2) Path to directory containing hippunfold outputs
hippunfold_dir: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/'

#3) Parameters for wb_command -surface-smoothing used to calculate displacement values from unsmoothed (or softSmooted) surfaces to the fully smoothed surface
surf_smoothing_strength: 0.9
surf_smoothing_iter: 50
surf_smoothing_soft_strength: 0.5
surf_smoothing_soft_iter: 10

#4) Additional hippunfold_metrics in a list to analyze in the pipeline. Possible values are 'curvature', 'gyrification', 'thickness', 'surfarea'
hippunfold_metrics_for_analysis: ['curvature', 'gyrification', 'thickness', 'surfarea']

### Preset inputs pulled from hippunfold_dir
#1) surface.surf.gii (inner midthickness outer)
surf_spaceT1w: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/surf/sub-{subject}_hemi-{hemi}_space-T1w_den-0p5mm_label-hipp_{surface}.surf.gii'
surf_spaceUnfold: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/surf/sub-{subject}_hemi-{hemi}_space-unfolded_den-0p5mm_label-hipp_{surface}.surf.gii'

#2) Subfield labels.label.gii (1D labelvalue for each subfield)
label_subfields_spaceT1w: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/surf/sub-{subject}_hemi-{hemi}_space-T1w_den-0p5mm_label-hipp_atlas-bigbrain_subfields.label.gii'

#3) HippunfoldMetrics.shape.gii (1D metric normalized metric at midthickness)
shape_metric_midthickness_spaceT1w: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/surf/sub-{subject}_hemi-{hemi}_space-T1w_den-0p5mm_label-hipp_{metric}.shape.gii'

#4) Transforms and Refvols for T1<-->Unfold
#4a) Xfm from T1w-->Unfold
xfm_fromT1w_toUnfold: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/warps/sub-{subject}_hemi-{hemi}_label-hipp_from-T1w_to-unfold_mode-image_xfm.nii.gz'
#4b) Refvol for Unfold
refvol_spaceUnfold: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/warps/sub-{subject}_space-unfold_label-hipp_refvol.nii.gz'

#4c) Xfm from Unfold-->T1w
xfm_fromUnfold_toT1w: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/warps/sub-{subject}_hemi-{hemi}_label-hipp_from-unfold_to-T1w_mode-image_xfm.nii.gz'
#4d) Refvol for T1w
refvol_spaceT1w: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/anat/sub-{subject}_desc-preproc_T1w.nii.gz'

#5) Inputs and params for subfield volumetry
dseg_subfields_bigbrain_spaceT1w: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset/derivatives/hippunfold_v1.2.0/hippunfold/sub-{subject}/anat/sub-{subject}_hemi-{hemi}_space-T1w_desc-subfields_atlas-bigbrain_dseg.nii.gz'
voxel_shape: [0.7, 0.7, 0.7]


#Grouped datasets dir
#all_datasets_bids_dir: '/home/ROBARTS/nchristidis/graham/scratch/digitations_all_datasets/combined_dataset'
#grad_coeff: '/project/6050199/akhanf/opt/grad/.coeff_AC84.grad'